# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2bf279b86100d5a24ef2effe96c6f823cfe2a4e07ac8ed39d8eae086d6f8c34b9824fc9b75dee783e22ad4b7f588e44dffb0ba1d2d9992b3f0f0f71841a2e0f0

test:
  secret_key_base: 9158cc9322a1003a7638d8f1a2f4150b7ff9ce3ef1bf8fcad9a234fa30f1819be71f0523e8bd2da9a84ecdf4250dd4bb9c07c6edf79396c7f2de784c10841964

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
